### ISSUE TITLE
Prepare the project for deployment to Maven Central

### ISSUE THREAD

**Issue by jkacer** [jkacer/pac4j-extensions#1]
We must fulfill all requirements in order to be able to deploy to Maven Central.
We will use an intermediate Sonatype repository - already configured.

Details described here:
- http://central.sonatype.org/pages/ossrh-guide.html
- http://central.sonatype.org/pages/apache-maven.html
- https://maven.apache.org/guides/mini/guide-central-repository-upload.html

Some more tutorials are on the Internet...

**Comment by jkacer** [comment]
A snapshot is already available here: https://oss.sonatype.org/content/groups/public/com/idc/webchannel/pac4j/

Just code, no source, no JavaDoc, not signed with GPG.
We need a stable dependency to use Maven Release.
And I don't want to release using "deploy -P release" when we still have a snapshot dependency.

**Comment by jkacer** [comment]
PAC4J 1.9.5 should be released on 2017-01-15, so more will be done after that date...
We must only switch the dependency and then test that the Release plugin can successfully create the release and deploy it to Sonatype Releases.

**Comment by jkacer** [comment]
Version 1.9.0 released and deployed to the Releases repository:
https://oss.sonatype.org/content/repositories/releases/com/idc/webchannel/pac4j/

**Comment by andrew-boutin** [comment]
Hey I was trying to use this library from Maven Central and it doesn't look like a .jar was ever published there. The same with your Sonatype repo.

- http://repo1.maven.org/maven2/com/idc/webchannel/pac4j/extensions/1.9.0/
-  https://oss.sonatype.org/content/repositories/releases/com/idc/webchannel/pac4j/extensions/1.9.0/

I think something is off with your publication steps.

**Comment by andrew-boutin** [comment]
Just found `com.idc.webchannel.pac4j:pac4j-saml-config-db:1.9.0`. Was trying to use `com.idc.webchannel.pac4j:extensions:1.9.0`.

**Comment by jkacer** [comment]
Hi Andrew! Yes, exactly, "extensions" is just the umbrella POM project, while the actual code is DB-based SAML configuration is in the JAR module "pac4j-saml-config-db".
You have already found yourself :-)
